'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Service_DesktopFamilyDetails
    
    '''<summary>
    '''frmDesktopFamilyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmDesktopFamilyDetails As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblServiceFamilyPn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceFamilyPn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFamilyPn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFamilyPn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlGPLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGPLM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkSPBAutoPub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSPBAutoPub As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRSLAutoPub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRSLAutoPub As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSeriesName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeriesName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rbBusiness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBusiness As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblProjectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPartner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPartner As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblPlatformName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatformName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPlatformName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatformName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFCS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFCS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDateEndOfService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEndOfService As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEndOfService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndOfService As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSaveSFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSFP As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''bntClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelSFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSFP As Global.System.Web.UI.WebControls.Button
End Class
