'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Service_ReportPlatformAssigmentAddDesktop
    
    '''<summary>
    '''frmReportPlatformAssigmentAddDesktop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmReportPlatformAssigmentAddDesktop As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblProducFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProducFamily As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstProductFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProductFamily As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblProductLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductLine As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstProductLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProductLine As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblODM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblODM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstODM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstODM As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblGPLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGPLM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstGPLM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstGPLM As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lnkBtAddProductFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtAddProductFamily As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''trNewProductFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNewProductFamily As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblProductFamilyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductFamilyName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProductFamilyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductFamilyName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddFamily As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelAddFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddFamily As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFamilyPn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFamilyPn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtServiceFamilyPn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceFamilyPn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPlatformName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatformName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPlatformName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatformName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPlatformDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatformDescription As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPlatformDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatformDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''bntAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAddAnother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAnother As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''bntClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFCS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFCS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDateEndOfService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateEndOfService As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEndOfService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndOfService As Global.System.Web.UI.WebControls.TextBox
End Class
