'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Service_ServiceAdvancedSearchReports
    
    '''<summary>
    '''frmServiceAdvancedSearchReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmServiceAdvancedSearchReports As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rdReportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdReportType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''btnSpareKitsPlus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSpareKitsPlus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportFormat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSpsToProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpsToProducts As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rtxtSpsNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtSpsNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSpspNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpspNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSpsNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpsNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSpsBom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpsBom As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rtxtSPSBom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtSPSBom As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSpsBom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpsBom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSPSBom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSPSBom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSpsByCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpsByCategory As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rlstSpareCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlstSpareCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSPSCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPSCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstSpareCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSpareCategory As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''pnlAvToSPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAvToSPS As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rdtxtAVNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdtxtAVNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblAVNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAVNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAVNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAVNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSkuToSpareKits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSkuToSpareKits As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rtxtSKUNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtSKUNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSKUNumebr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKUNumebr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSKUNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSKUNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlFamilyToSkuToSparekits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFamilyToSkuToSparekits As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rCustomValtxtSkuNumberProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rCustomValtxtSkuNumberProduct As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''chkUnselectProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUnselectProducts As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblProductos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProducts As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSkuNumberProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSkuNumberProduct As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlUsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUsedBy As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rdUsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdUsedBy As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblUsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rUsedByTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rUsedByTxt As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rUsedByProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rUsedByProduct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtUsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsedBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lstUsedByProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUsedByProducts As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblMaxPartNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxPartNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUsedBySku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsedBySku As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtUsedBySKU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsedBySKU As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRSLChangeLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRSLChangeLog As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RewRSLChangeLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RewRSLChangeLog As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''chkProductsRSLChangeLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProductsRSLChangeLog As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblProductFamilies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductFamilies As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstProductFamilies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProductFamilies As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''pnlAvBomReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAvBomReport As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblBomAvNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBomAvNumbers As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBomAvNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBomAvNumbers As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rtxtBomAvNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtxtBomAvNumbers As Global.System.Web.UI.WebControls.RequiredFieldValidator
End Class
