'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Service_ServiceAdvancedSearchReportsSummary
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gvSpareKitsByCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSpareKitsByCategory As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvSpareKitsBom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSpareKitsBom As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvReportAvNumberToSps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReportAvNumberToSps As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvReportSkuToSpareKits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReportSkuToSpareKits As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvReportProductToSkuToSparekits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReportProductToSkuToSparekits As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvUsedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUsedBy As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvRSLChangeLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRSLChangeLog As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblConfidential control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfidential As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastRun As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastRunDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastRunDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''msgSearchNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgSearchNoData As Global.System.Web.UI.WebControls.Label
End Class
