'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Service_SKUBOMAS
    
    '''<summary>
    '''filterForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filterForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''tblProfileTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblProfileTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''ddlRptProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRptProfile As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkBtnApplyProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnApplyProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnAddProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnAddProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnUpdateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnUpdateProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnDeleteProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnDeleteProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnRenameProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnRenameProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnShareProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnShareProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtnRemoveSharedProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnRemoveSharedProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblProfileStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkBxIncludeRemSProfs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBxIncludeRemSProfs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tblFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFilterOptions As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblFilterOptions0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFilterOptions0 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtbxSFPNS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxSFPNS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbxKMATS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxKMATS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdoProdDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoProdDiv As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lstbxBrands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbxBrands As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtbxSKUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxSKUS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbxSKUAVS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxSKUAVS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkbxAllSKUAVs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxAllSKUAVs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxSKUAVLogFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSKUAVLogFilter As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxGeoNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxGeoNA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxGeoLA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxGeoLA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxGeoAPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxGeoAPJ As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxGeoEMEA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxGeoEMEA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lstbxOSSPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbxOSSPs As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''tblFilterOptions1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFilterOptions1 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtbxSKs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxSKs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkbxSKGeoNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSKGeoNA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxSKGeoLA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSKGeoLA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxSKGeoAPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSKGeoAPJ As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxSKGeoEMEA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSKGeoEMEA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lstbxCats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstbxCats As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtbxAVS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxAVS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkbxAllAVs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxAllAVs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtbxSAs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxSAs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtbxComps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxComps As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkbxSPBLogFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxSPBLogFilter As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxAdded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxAdded As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkbxUpdated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkbxUpdated As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtbxFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxFromDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkBtnFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnFromDate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtbxToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbxToDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkBtnToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnToDate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlActionDateColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActionDateColumn As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlRowsPerPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRowsPerPage As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''selectedColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''allColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents allColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ddlReportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''selectedCols control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedCols As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''orderCols control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orderCols As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''profileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profileName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''continueAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents continueAction As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''profileFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profileFlag As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''resetFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resetFlag As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''dsBrands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBrands As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCategories As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''odsListPartners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsListPartners As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsAvailableColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAvailableColumns As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsDateColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDateColumns As Global.System.Web.UI.WebControls.SqlDataSource
End Class
