'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search_SpareKitDetails
    
    '''<summary>
    '''frmAdvSearchDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAdvSearchDetail As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSpareKitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareKitNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSKCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSpareKitDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareKitDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSpareKitNumberValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareKitNumberValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSKCategoryValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKCategoryValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSpareKitDescValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpareKitDescValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMaterialType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterialType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRevisionLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRevisionLevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCrossPlantStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCrossPlantStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOSSPOrderable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOSSPOrderable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMaterialTypeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterialTypeValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDivisionValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivisionValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRevisionLevelValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRevisionLevelValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCrossPlantStatusValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCrossPlantStatusValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOSSPOrderableValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOSSPOrderableValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''msgSearchNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgSearchNoData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dgData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgData As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''lblConfidential control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfidential As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastRun As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLastRunDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastRunDate As Global.System.Web.UI.WebControls.Label
End Class
