'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search_SpareKit

    '''<summary>
    '''frmSKUSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSKUSearch As System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As System.Web.UI.UpdatePanel

    '''<summary>
    '''lblProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfile As System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlReportProfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportProfiles As System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbAddProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAddProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbUpdateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdateProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDeleteProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeleteProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbRenameProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRenameProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbShareProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShareProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbRemoveProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRemoveProfile As System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblProfileOwnerHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileOwnerHdr As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProfileOwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileOwnerName As System.Web.UI.WebControls.Label

    '''<summary>
    '''hidProfileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProfileName As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidProfileId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProfileId As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCategories As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidProductNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProductNames As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidSkuNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSkuNumber As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidOSSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidOSSP As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidServiceFamPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidServiceFamPartNum As System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSummaryReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummaryReport As System.Web.UI.WebControls.Button

    '''<summary>
    '''btnServiceBomReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnServiceBomReport As System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHow As System.Web.UI.WebControls.Label

    '''<summary>
    '''rdProductType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdProductType As System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductName As System.Web.UI.WebControls.Label

    '''<summary>
    '''lstProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstProducts As System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblProductOnlySummamry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductOnlySummamry As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSKCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKCategory As System.Web.UI.WebControls.Label

    '''<summary>
    '''lstSpareCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSpareCategory As System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOSSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOSSP As System.Web.UI.WebControls.Label

    '''<summary>
    '''lstOSSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstOSSP As System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKMAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKMAT As System.Web.UI.WebControls.Label

    '''<summary>
    '''txtKMAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKMAT As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSKUNumebr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKUNumebr As System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSKUNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSKUNumber As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMaxRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxRows As System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMaxRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxRows As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportFormat As System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportFormat As System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSKUGeo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSKUGeo As System.Web.UI.WebControls.Label

    '''<summary>
    '''chkSKUGeo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSKUGeo As System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpsGeo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpsGeo As System.Web.UI.WebControls.Label

    '''<summary>
    '''chkSpsGeo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSpsGeo As System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSkuDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkuDate As System.Web.UI.WebControls.Label

    '''<summary>
    '''DatepickerSKUStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatepickerSKUStart As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSkuDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkuDateTo As System.Web.UI.WebControls.Label

    '''<summary>
    '''DatepickerSKUEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatepickerSKUEnd As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpsDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpsDate As System.Web.UI.WebControls.Label

    '''<summary>
    '''DatepickerSPSStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatepickerSPSStart As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSPSDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPSDateTo As System.Web.UI.WebControls.Label

    '''<summary>
    '''DatepickerSPSEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DatepickerSPSEnd As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblServiceFamPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiceFamPartNum As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSRServiceFamPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSRServiceFamPartNum As System.Web.UI.WebControls.Label

    '''<summary>
    '''txtServiceFamPartNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtServiceFamPartNum As System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpsNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpsNumbers As System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpsNumbersSumReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpsNumbersSumReport As System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSpsNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpsNumbers As System.Web.UI.WebControls.TextBox
End Class
