<%
	Dim AppDirectory : AppDirectory = Session("ApplicationRoot") 
%>
<link type="text/css" href="<%=AppDirectory%>/style/redmond/jquery-ui-1.8.7.custom.css" rel="stylesheet" />
<link type="text/css" href="<%=AppDirectory%>/style/shared.css" rel="stylesheet" />
<script type="text/javascript" src="<%=AppDirectory%>/includes/client/jquery.min.js"></script>
<script type="text/javascript" src="<%=AppDirectory%>/includes/client/jquery-ui.min.js"></script>
<script type="text/javascript" src="<%=AppDirectory%>/Scripts/shared_functions.js" ></script>
