<%
'--DECLARE CONSTANTS declared in original VB6 DLL JF Common file----------------------
Const tcAMOModuleDivision = 99
Const tsAMOStatus = 23
Const tcHWModuleCategory = 13
Const tcSWModuleCategory = 28
Const tcHWSWModuleCategory = -1
Const tcHWSWModuleCategory_NoAll = -101
Const tcModuleType = 22
Const tcAMOProductLine = 98
Const tcMOLModuleDivision = 19

Const cg_lngCONN_TIMEOUT = 120
Const cg_lngLEN_INT = 4
Const cg_lngLEN_USERNAME = 18
%>