'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Query_schedule
    
    '''<summary>
    '''body control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents body As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfile As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlReportProfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportProfiles As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbAddProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAddProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbUpdateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUpdateProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbDeleteProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeleteProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbRenameProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRenameProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbShareProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbShareProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbRemoveProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRemoveProfile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblProfileOwnerHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileOwnerHdr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProfileOwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileOwnerName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hidProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProducts As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidGroups As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidProfileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProfileName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidProfileId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidProfileId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnSummaryReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSummaryReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnHistoryReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHistoryReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProducts As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProducts As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblProductGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductGroups As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbProductGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProductGroups As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblInlcudeSystemTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInlcudeSystemTeam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbIncludeSystemTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbIncludeSystemTeam As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlReportFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportFormat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnRefreshMilestones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshMilestones As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMilestones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMilestones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMilestoneNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMilestoneNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rptMilestones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMilestones As Global.System.Web.UI.WebControls.Repeater
End Class
